# Generated by Django 4.2.9 on 2024-02-03 17:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("progress", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Tracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("current_point", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("traveled_path", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("roll", models.FloatField()),
                ("pitch", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "track_expected_path",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_work_expected_path",
                        to="work.works",
                    ),
                ),
                (
                    "track_work_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_work_work_name",
                        to="work.works",
                    ),
                ),
            ],
        ),
    ]
