# Generated by Django 4.2.9 on 2024-02-19 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("progress", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("current_point", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                (
                    "traveled_path",
                    django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
                ),
                ("start_point_t", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("end_point_t", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("markers", django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ("roll", models.FloatField(blank=True, null=True)),
                ("pitch", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
