# Generated by Django 4.2.9 on 2024-02-11 09:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking",
            name="track_expected_path",
        ),
        migrations.RemoveField(
            model_name="tracking",
            name="track_work_name",
        ),
        migrations.AddField(
            model_name="tracking",
            name="end_point_t",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="tracking",
            name="markers",
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="tracking",
            name="start_point_t",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="progress",
            name="progress",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="pitch",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="roll",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracking",
            name="traveled_path",
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
    ]
