# Generated by Django 4.2.9 on 2024-02-03 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Works",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("work_name", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("end_point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("expected_path", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("user_memo", models.TextField(blank=True)),
                ("estimated_hours", models.IntegerField(default=0, help_text="예상 작업시간: 시간")),
                ("estimated_minutes", models.IntegerField(default=0, help_text="예상 작업시간: 분")),
                (
                    "crop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_farm_crop",
                        to="farm.farmfield",
                    ),
                ),
                (
                    "work_fields",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_farm_farmfield",
                        to="farm.farmfield",
                    ),
                ),
                (
                    "work_machine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_farm_machine",
                        to="farm.machine",
                    ),
                ),
            ],
        ),
    ]
