# Generated by Django 4.2.9 on 2024-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="works",
            name="solution_on",
            field=models.BooleanField(default=True),
        ),
    ]
