# Generated by Django 4.2.9 on 2024-02-09 08:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0002_remove_machine_farm_machine_user_delete_weather_and_more"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="works",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="works",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="works",
            name="work_machine",
        ),
        migrations.AddField(
            model_name="works",
            name="battery",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="contents",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="works",
            name="end_date_day",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="end_date_month",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="end_date_year",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="works",
            name="machine_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="works",
            name="machine_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="works",
            name="start_date_day",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="start_date_month",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="works",
            name="start_date_year",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="works",
            name="crop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm_farm_crop",
                to="farm.farmfield",
            ),
        ),
        migrations.AlterField(
            model_name="works",
            name="end_point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="works",
            name="expected_path",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="works",
            name="start_point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
