# Generated by Django 4.2.9 on 2024-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_remove_works_end_date_remove_works_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="works",
            name="crop",
            field=models.CharField(null=True),
        ),
    ]
