# Generated by Django 4.2.9 on 2024-02-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_works_solution_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="works",
            name="solution_on",
        ),
    ]
