# Generated by Django 4.2.9 on 2024-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workdiary", "0002_workdiary_is_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workdiary",
            name="selected_date",
        ),
        migrations.AddField(
            model_name="workdiary",
            name="fin_date",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
