# Generated by Django 4.2.9 on 2024-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_name_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="realname",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="Real name"),
        ),
    ]
