# Generated by Django 4.2.9 on 2024-02-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_realname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="realname",
        ),
    ]
