# Generated by Django 4.2.9 on 2024-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_realname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="이름"),
        ),
    ]
