# Generated by Django 4.2.9 on 2024-02-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        ("farm", "0001_initial"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("selected_date", models.DateField()),
                ("mymemo", models.TextField(blank=True)),
                (
                    "home_farmfield",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_farm_farmfield",
                        to="farm.farmfield",
                    ),
                ),
                (
                    "home_machines",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_farm_machine",
                        to="farm.machine",
                    ),
                ),
                (
                    "home_tracking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_tracking_tracking",
                        to="tracking.tracking",
                    ),
                ),
                (
                    "home_weather",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoem_farm_weather",
                        to="farm.weather",
                    ),
                ),
                (
                    "home_work",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_work_works",
                        to="work.works",
                    ),
                ),
            ],
        ),
    ]
