# Generated by Django 4.2.9 on 2024-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="home_tracking",
        ),
        migrations.AlterField(
            model_name="home",
            name="mymemo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="home",
            name="selected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
