# Generated by Django 4.2.9 on 2024-02-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmfield",
            name="field_name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
