# Generated by Django 4.2.9 on 2024-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="location_name_detail",
            field=models.CharField(null=True),
        ),
    ]
