# Generated by Django 4.2.9 on 2024-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_home_home_machines_remove_home_home_weather"),
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="farm_machine_user",
        ),
        migrations.DeleteModel(
            name="Weather",
        ),
        migrations.AddField(
            model_name="farmfield",
            name="humidity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="is_rain",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="rain_sh",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="sky_sh",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="temperature",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="weather_date",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="weather_time",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="wind_direction",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="wind_speed",
            field=models.FloatField(null=True),
        ),
    ]
