# Generated by Django 4.2.9 on 2024-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_farmfield_location_name_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="max_tem",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="min_tem",
            field=models.IntegerField(null=True),
        ),
    ]
