# Generated by Django 4.2.9 on 2024-02-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_farmfield_max_tem_farmfield_min_tem"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="one_after_sky_sh",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="three_after_sky_sh",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="two_after_sky_sh",
            field=models.CharField(null=True),
        ),
    ]
