# Generated by Django 4.2.9 on 2024-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_delete_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="user_memo",
            field=models.CharField(null=True),
        ),
    ]
