# Generated by Django 4.2.9 on 2024-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0004_farmfield_user_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmfield",
            name="user_memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
