# Generated by Django 4.2.9 on 2024-02-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0005_farmfield_is_selected_alter_farmfield_user_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmfield",
            name="location",
            field=models.JSONField(null=True),
        ),
    ]
