# Generated by Django 4.2.9 on 2024-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0005_farmfield_location_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="solution_on",
            field=models.BooleanField(default=True),
        ),
    ]
