# Generated by Django 4.2.9 on 2024-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0006_farmfield_solution_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmfield",
            name="solution_on",
            field=models.BooleanField(default=False),
        ),
    ]
